#!/usr/bin/env python3
"""Apply the minimal QoS1/effect-path idle-sync singleton ablation to fd37ed3."""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

EXPECTED_SHA256 = "78b771ddba5db5e7c8f0ddafce5f04fd4ac370e845e39b06d615b47d15e5b8bd"

path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("src/mqttium/api/_delivery.py")
original = path.read_text()
actual = hashlib.sha256(path.read_bytes()).hexdigest()
if actual != EXPECTED_SHA256:
    raise SystemExit(f"unexpected _delivery.py source: {actual}")

old_body = '''    def deliver_message_batch_inline(\n        self,\n        effects: deque[EngineEffect],\n        callback: Callable[[Message], Any] | None,\n    ) -> int:\n        """Admit a consecutive eligible prefix; never run application code.\n\n        The effect owner may finish admission synchronously without creating a\n        flusher. User execution belongs exclusively to the callback worker.\n        Iterator/callback capacity is preflighted once for the whole prefix.\n        No user code or suspension can invalidate that preflight.\n        Persisted deliveries and exact-byte reservations retain the slow path.\n        """\n        callback_delivery, iterator_delivery = self._modes(callback)\n        if not callback_delivery and not iterator_delivery:\n            return 0\n        cb = callback if callback_delivery else None\n        capacity = len(effects)\n        if iterator_delivery:\n            capacity = min(capacity, self.messages_queue.maxsize - self.messages_queue.qsize())\n        if cb is not None:\n            capacity = min(capacity, self.callback_queue.maxsize - self.callback_queue.qsize())\n        ready = False\n        applied = 0\n        for effect in effects:\n            if applied >= capacity:\n                break\n            if effect.kind not in (EffectKind.MESSAGE, EffectKind.DECODED_MESSAGE):\n                break\n            message: Message = effect.data\n            size = effect.decoded_property_wire_size\n            if effect.requires_delivery_mark or not (\n                self._is_small(message) if size is None else self._is_small_decoded(message, size)\n            ):\n                break\n            if cb is not None and not ready:\n                self.ensure_callback_worker()\n                ready = True\n            if iterator_delivery:\n                self.messages_queue.put_nowait(message)\n            if cb is not None:\n                self.callback_queue.put_nowait((cb, (message,), None))\n            applied += 1\n        if applied and iterator_delivery:\n            self.message_ready.set()\n        return applied\n'''

new_body = '''    def _small_message_effect(self, effect: EngineEffect) -> Message | None:\n        if effect.kind not in (EffectKind.MESSAGE, EffectKind.DECODED_MESSAGE):\n            return None\n        message: Message = effect.data\n        size = effect.decoded_property_wire_size\n        if effect.requires_delivery_mark or not (\n            self._is_small(message) if size is None else self._is_small_decoded(message, size)\n        ):\n            return None\n        return message\n\n    def deliver_message_batch_inline(\n        self,\n        effects: deque[EngineEffect],\n        callback: Callable[[Message], Any] | None,\n    ) -> int:\n        """Admit an eligible prefix, with one narrow idle-sync fast path.\n\n        A callback-only prefix containing exactly one admissible message may\n        execute synchronously when no callback is active or queued. Consecutive\n        messages, async callbacks, iterator+callback delivery and reentrant work\n        retain the ordinary bounded worker path.\n        """\n        callback_delivery, iterator_delivery = self._modes(callback)\n        if (not callback_delivery and not iterator_delivery) or not effects:\n            return 0\n        cb = callback if callback_delivery else None\n\n        if cb is not None and not iterator_delivery and self.can_dispatch_callback_inline(cb):\n            first = self._small_message_effect(effects[0])\n            if first is not None and (\n                len(effects) == 1 or self._small_message_effect(effects[1]) is None\n            ):\n                self.dispatch_callback_inline(cb, first)\n                return 1\n\n        capacity = len(effects)\n        if iterator_delivery:\n            capacity = min(capacity, self.messages_queue.maxsize - self.messages_queue.qsize())\n        if cb is not None:\n            capacity = min(capacity, self.callback_queue.maxsize - self.callback_queue.qsize())\n        ready = False\n        applied = 0\n        for effect in effects:\n            if applied >= capacity:\n                break\n            message = self._small_message_effect(effect)\n            if message is None:\n                break\n            if cb is not None and not ready:\n                self.ensure_callback_worker()\n                ready = True\n            if iterator_delivery:\n                self.messages_queue.put_nowait(message)\n            if cb is not None:\n                self.callback_queue.put_nowait((cb, (message,), None))\n            applied += 1\n        if applied and iterator_delivery:\n            self.message_ready.set()\n        return applied\n'''
if original.count(old_body) != 1:
    raise SystemExit("deliver_message_batch_inline source did not match exactly once")
text = original.replace(old_body, new_body)
path.write_text(text)
print(hashlib.sha256(path.read_bytes()).hexdigest())
