"""Constructor configuration contracts and connection-scoped negotiation."""

from __future__ import annotations

from dataclasses import fields

import pytest

from mqttium.api.async_client import AsyncClient
from mqttium.codec.buffer import DEFAULT_MAX_PACKET_SIZE
from mqttium.codec.vbi import decode_vbi
from mqttium.enums import MQTTProtocolVersion
from mqttium.protocol.engine import EngineConfig, ProtocolEngine
from mqttium.protocol.negotiated import NegotiatedSettings
from mqttium.protocol.reconnect import ReconnectPolicy


# Every public constructor field is classified deliberately. Adding a field to
# EngineConfig must update this table instead of silently inheriting either
# runtime-mutability policy.
_ENGINE_CONFIG_RUNTIME_MUTABILITY = {
    "client_id": False,
    "protocol": False,
    "clean_start": False,
    "keepalive": True,
    "username": True,
    "password": True,
    "max_inbound_inflight": False,
    "max_outbound_inflight": False,
    "max_unacknowledged_messages": True,
    "max_unacknowledged_bytes": True,
    "max_inbound_inflight_bytes": True,
    "connect_properties": False,
    "will": True,
    "will_properties": True,
    "maximum_packet_size": False,
    "topic_alias_maximum": False,
    "manual_ack": False,
    "accept_auth": True,
}


@pytest.mark.parametrize(
    ("field", "value"),
    [
        ("keepalive", -1),
        ("keepalive", 65536),
        ("max_inbound_inflight", 0),
        ("max_inbound_inflight", 65536),
        ("max_outbound_inflight", 0),
        ("max_inbound_inflight_bytes", -1),
        ("maximum_packet_size", 1),
        ("topic_alias_maximum", -1),
        ("topic_alias_maximum", 65536),
    ],
)
def test_engine_config_rejects_invalid_ranges(field: str, value: int) -> None:
    with pytest.raises(ValueError):
        EngineConfig(**{field: value})


def test_engine_configuration_is_frozen() -> None:
    config = EngineConfig()
    ProtocolEngine(config)
    for field in fields(config):
        with pytest.raises(AttributeError):
            setattr(config, field.name, getattr(config, field.name))
    assert not hasattr(config, "update")


@pytest.mark.parametrize(
    "kwargs",
    [
        {"max_write_queue_messages": 0},
        {"max_write_queue_bytes": 0},
        {"max_iterator_messages": 0},
        {"max_inbound_inflight_bytes": -1},
        {"connect_timeout": 0},
        {"subscribe_timeout": 0},
        {"auth_timeout": 0},
        {"ping_timeout": 0},
        {"iterator_admission_timeout": 0},
        {"message_delivery": "callback", "max_iterator_messages": 1},
        {"message_delivery": "callback", "max_iterator_bytes": 1},
        {"message_delivery": "callback", "iterator_admission_timeout": 1.0},
        {"client_id": b"bad"},
        {"username": b"bad"},
        {"password": object()},
    ],
)
def test_async_client_rejects_invalid_configuration(kwargs) -> None:
    with pytest.raises(ValueError):
        AsyncClient(**kwargs)


@pytest.mark.parametrize(
    "kwargs",
    [
        {"initial_delay": -1},
        {"multiplier": 0.5},
        {"initial_delay": 2, "max_delay": 1},
        {"max_retries": -1},
        {"stable_after": -1},
    ],
)
def test_reconnect_policy_rejects_invalid_configuration(kwargs) -> None:
    with pytest.raises(ValueError):
        ReconnectPolicy(**kwargs)


def test_default_local_packet_limit_is_announced_in_mqtt5_connect() -> None:
    client = AsyncClient(protocol=MQTTProtocolVersion.MQTTv5)
    assert client._decoder.max_packet_size == DEFAULT_MAX_PACKET_SIZE
    assert client._engine.config.maximum_packet_size == DEFAULT_MAX_PACKET_SIZE

    wire = client._engine.begin_connect()
    remaining_length, pos = decode_vbi(wire, 1)
    body = wire[pos : pos + remaining_length]
    # Decode enough of CONNECT to inspect the properties through the packet
    # generated by the engine: the value must be present on the wire.
    assert DEFAULT_MAX_PACKET_SIZE.to_bytes(4, "big") in body


def test_negotiated_capabilities_reset_before_new_connection() -> None:
    engine = ProtocolEngine()
    engine.negotiated = NegotiatedSettings(
        maximum_qos=0,
        retain_available=False,
        maximum_packet_size=128,
    )

    engine.begin_connect()

    assert engine.negotiated.maximum_qos == 2
    assert engine.negotiated.retain_available is True
    assert engine.negotiated.maximum_packet_size is None
