"""Constructor configuration contracts and connection-scoped negotiation."""

from __future__ import annotations

from dataclasses import fields

import pytest

from mqttium.api.async_client import AsyncClient
from mqttium.codec.buffer import DEFAULT_MAX_PACKET_SIZE
from mqttium.codec.vbi import decode_vbi
from mqttium.enums import MQTTProtocolVersion
from mqttium.protocol.engine import EngineConfig, ProtocolEngine
from mqttium.protocol.negotiated import NegotiatedSettings
from mqttium.protocol.reconnect import ReconnectPolicy


# Every public constructor field is classified deliberately. Adding a field to
# EngineConfig must update this table instead of silently inheriting either
# runtime-mutability policy.
_ENGINE_CONFIG_RUNTIME_MUTABILITY = {
    "client_id": False,
    "protocol": False,
    "clean_start": False,
    "keepalive": True,
    "username": True,
    "password": True,
    "local_receive_maximum": False,
    "max_outbound_inflight": False,
    "max_pending_outbound_messages": True,
    "max_pending_outbound_bytes": True,
    "max_pending_inbound_bytes": True,
    "connect_properties": False,
    "will": True,
    "will_properties": True,
    "maximum_packet_size": False,
    "topic_alias_maximum": False,
    "manual_ack": False,
    "accept_auth": True,
}


@pytest.mark.parametrize(
    ("field", "value"),
    [
        ("keepalive", -1),
        ("keepalive", 65536),
        ("local_receive_maximum", 0),
        ("local_receive_maximum", 65536),
        ("max_outbound_inflight", 0),
        ("max_pending_inbound_bytes", -1),
        ("maximum_packet_size", 1),
        ("topic_alias_maximum", -1),
        ("topic_alias_maximum", 65536),
    ],
)
def test_engine_config_rejects_invalid_ranges(field: str, value: int) -> None:
    with pytest.raises(ValueError):
        EngineConfig(**{field: value})


def test_engine_config_runtime_mutability_is_explicit_and_exhaustive() -> None:
    config_fields = {field.name for field in fields(EngineConfig) if field.init}
    assert config_fields == set(_ENGINE_CONFIG_RUNTIME_MUTABILITY)

    config = EngineConfig()
    ProtocolEngine(config)
    assert config._attached

    for name, runtime_mutable in _ENGINE_CONFIG_RUNTIME_MUTABILITY.items():
        current = getattr(config, name)
        if runtime_mutable:
            config.update(**{name: current})
        else:
            with pytest.raises(AttributeError, match="require a new ProtocolEngine"):
                config.update(**{name: current})


@pytest.mark.parametrize(
    "kwargs",
    [
        {"max_outbound_messages": 0},
        {"max_outbound_bytes": 0},
        {"max_pending_messages": 0},
        {"max_pending_inbound_bytes": -1},
        {"ack_timeout": 0},
        {"ping_timeout": 0},
        {"client_id": b"bad"},
        {"username": b"bad"},
        {"password": object()},
    ],
)
def test_async_client_rejects_invalid_configuration(kwargs) -> None:
    with pytest.raises(ValueError):
        AsyncClient(**kwargs)


@pytest.mark.parametrize(
    "kwargs",
    [
        {"initial_delay": -1},
        {"multiplier": 0.5},
        {"initial_delay": 2, "max_delay": 1},
        {"max_retries": -1},
        {"stable_after": -1},
        {"connect_timeout": 0},
    ],
)
def test_reconnect_policy_rejects_invalid_configuration(kwargs) -> None:
    with pytest.raises(ValueError):
        ReconnectPolicy(**kwargs)


def test_default_local_packet_limit_is_announced_in_mqtt5_connect() -> None:
    client = AsyncClient(protocol=MQTTProtocolVersion.MQTTv5)
    assert client._decoder.max_packet_size == DEFAULT_MAX_PACKET_SIZE
    assert client._engine.config.maximum_packet_size == DEFAULT_MAX_PACKET_SIZE

    wire = client._engine.begin_connect()
    remaining_length, pos = decode_vbi(wire, 1)
    body = wire[pos : pos + remaining_length]
    # Decode enough of CONNECT to inspect the properties through the packet
    # generated by the engine: the value must be present on the wire.
    assert DEFAULT_MAX_PACKET_SIZE.to_bytes(4, "big") in body


def test_negotiated_capabilities_reset_before_new_connection() -> None:
    engine = ProtocolEngine()
    engine.negotiated = NegotiatedSettings(
        maximum_qos=0,
        retain_available=False,
        maximum_packet_size=128,
    )

    engine.begin_connect()

    assert engine.negotiated.maximum_qos == 2
    assert engine.negotiated.retain_available is True
    assert engine.negotiated.maximum_packet_size is None
